### ISSUE TITLE
500 Error After Installation

### ISSUE THREAD

**Issue by mattheworres** [imagegenius/docker-obico#26]
Howdy, just trying to get my own container stood up via CA and I get 500 errors when I attempt to access the application via browser. Second error I think is just a missing favicon and not actually germane (tho it likely fails to serve bc the server is not working):

```
[2024-12-10 01:20:16,416: INFO/MainProcess] mingle: all alone
[2024-12-10 01:20:16,427: INFO/MainProcess] celery@c5d01b90dd4e ready.
django.request ERROR    Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/sites/models.py", line 39, in _get_site_by_request
    SITE_CACHE[host] = self.get(domain__iexact=host)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 496, in get
    raise self.model.DoesNotExist(
django.contrib.sites.models.Site.DoesNotExist: Site matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 43, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/usr/local/lib/python3.10/dist-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "/usr/local/lib/python3.10/dist-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/allauth/account/views.py", line 84, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/allauth/account/mixins.py", line 40, in dispatch
    response = super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/allauth/account/mixins.py", line 59, in get
    response = super().get(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/edit.py", line 144, in get
    return self.render_to_response(self.get_context_data())
  File "/usr/local/lib/python3.10/dist-packages/allauth/account/views.py", line 106, in get_context_data
    site = get_current_site(self.request)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/sites/shortcuts.py", line 14, in get_current_site
    return Site.objects.get_current(request)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/sites/models.py", line 61, in get_current
    return self._get_site_by_request(request)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/sites/models.py", line 45, in _get_site_by_request
    SITE_CACHE[domain] = self.get(domain__iexact=domain)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 496, in get
    raise self.model.DoesNotExist(
django.contrib.sites.models.Site.DoesNotExist: Site matching query does not exist.
django.request WARNING  Not Found: /favicon.ico
```

**Comment by DrFate09** [comment]
@mattheworres I found the solution to solve the "Site matching query does not exist" 500 error (this applies to Unraid).

Instructions:

1. Open obico console
2. In the console, input "cd /app/obico/backend/config"
3. Install Nano Text Editor, input "apt-get install nano"
4. Open the settings.py file, input "nano settings.py"
5. Insert "SITE_ID = 1" in the settings.py file (see screenshot below)

![obico_console](https://github.com/user-attachments/assets/a53a91db-d9d4-4b59-81e6-dac2881850b5)

6. Save the file
7. Restart the obico Docker container
8. Fixed!

**Comment by hydazz** [comment]
This is supposed to be handled by https://github.com/imagegenius/docker-obico/blob/9c6cd29ed16140d08fc1997d7694440d74cfa291/root/etc/s6-overlay/s6-rc.d/init-config-obico/run#L15-L23

I'm unsure why its not working again. the solution above may work but wont persist through restarts, i also suggest you hide secrets before posting screenshots @DrFate09  🤨

**Comment by DrFate09** [comment]
@hydazz Thanks for the heads-up, I edited the screenshot.

Anyways, I could not get past the 500 error no matter what I did (I am using the latest non-CUDA docker image). I found the fix on the Obico Discord. So far, the fix has been persistent between restarts on my Unraid server.

**Comment by mattheworres** [comment]
> @hydazz Thanks for the heads-up, I edited the screenshot.
> 
> Anyways, I could not get past the 500 error no matter what I did (I am using the latest non-CUDA docker image). I found the fix on the Obico Discord. So far, the fix has been persistent between restarts on my Unraid server.

I think he just means when you update the container - which was where my mind went, too. Thanks for cross-posting the fix here, quite helpful until we can solve the issue for-good. At least we can keep using our containers!

**Comment by mattheworres** [comment]
Just wanted to come back and say, the `SITE_ID = 1` in `settings.py` worked for me, but only once I switched back to the (CUDA, but I suspect it's similar in the non-Nvidia) build `cuda-471c0364-ig5` - something else had broken in newer images that the container wasn't even receiving requests, it seems. Was finally able to see my container instance stand up last night. Thanks, @DrFate09 !!

**Comment by hydazz** [comment]
Can someone verify that the error goes away when appending `:3334` to the end of `HOST_IP`, so you're ending up with something like `192.168.1.5:3334`

**Comment by DrFate09** [comment]
> Can someone verify that the error goes away when appending `:3334` to the end of `HOST_IP`, so you're ending up with something like `192.168.1.5:3334`

This fixed the issue for me. I had to remove the "/example.com" to make it work.

**Comment by hydazz** [comment]
fixed documentation to make things clearer, `HOST_IP` must be set correctly to the domain **OR** IP and port used to access the obico frontend

**Comment by mattheworres** [comment]
So, I have the HOST_IP set correctly (I use nginx to reverse proxy from IP:PORT to HOSTNAME, but I've also set IP:PORT directly and both work), but in the latest build for the cuda branch (I see both were just published 16 hours ago ATOW) does not even properly perform a correct response to accept connections as a webserver. 

When I open the logs, its generating the same messages so quickly, it's hard for me to even scroll through the message fast enough before the buffer is filled again with more debug info, so Django can't even stand up. 

I did a quick CTRL+A CTRL+C (actually CMD, but whatever) and after finally getting to focus on the text, I immediately see this pop out to me, seems fairly important is missing or misconfigured:

`ImportError: cannot import name 'MoonrakerApp' from 'app' (/app/obico/backend/app/__init__.py)`

**Comment by mattheworres** [comment]
Ah! Classic PEBCAK here on my part. Your fix works!

Edit: Wanted to make sure that was there so you weren't looking into it anymore wasting time on it. With the latest image (fresh, so your fix to the moonraker path was actually applied) and the server starts up immediately. Thanks for such a quick fix!
